### ISSUE TITLE
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

### ISSUE THREAD

**Issue by ameenonnet123** [TCNOco/TcNo-TCHT#10]
getting error when executing , can you help what is the issue.

PS C:\TCHT\privateGPT> .\run-privategpt.bat
Using embedded DuckDB with persistence: data will be stored in: db
llama.cpp: loading model from models/ggml-vic13b-uncensored-q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1000
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9031.70 MB (+ 1608.00 MB per state)
.
llama_init_from_file: kv self size  =  781.25 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |

Enter a query: name
Traceback (most recent call last):
  File "C:\TCHT\privateGPT\privateGPT.py", line 72, in <module>
    main()
  File "C:\TCHT\privateGPT\privateGPT.py", line 49, in main
    res = qa(query)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 119, in _call
    docs = self._get_docs(question)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\base.py", line 377, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 182, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 229, in similarity_search_with_score
    results = self.__query_collection(
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\models\Collection.py", line 227, in query
    return self._client._query(
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\local.py", line 437, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\db\clickhouse.py", line 585, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "C:\Users\mdame\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\db\index\hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

**Comment by TCNOco** [comment]
This is an issue with [privateGPT](https://github.com/imartinez/privateGPT), not my installer script.
The best I can do is refer you to the [privateGPT Issues section](https://github.com/imartinez/privateGPT/issues) where you can search for `chromadb.errors.NoIndexException`.

From what I see you just need to run `ingest.py` and launch privateGPT again to use documents, as the chroma database has not yet been created (no documents ingested first before trying to use it)
