### ISSUE TITLE
Uh oh [KeyError: 'serialized_input']

### ISSUE THREAD

**Issue by DOGMANTC** [TCNOco/TcNo-TCHT#6]
Which one do you want to load? 1-2

2

INFO:Loading TheBloke_vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g...
INFO:Found the following quantized model: models\TheBloke_vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g\vicuna-AlekseyKorshuk-7B-GPTQ-4bit-128g.no-act-order.pt
INFO:Loaded the model in 6.68 seconds.
INFO:Loading the extension "gallery"...
Traceback (most recent call last):
  File "C:\Users\QUACK\Downloads\roooooflllll\oobabooga_windows\text-generation-webui\server.py", line 885, in <module>
    create_interface()
  File "C:\Users\QUACK\Downloads\roooooflllll\oobabooga_windows\text-generation-webui\server.py", line 472, in create_interface
    with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui.chat_css, analytics_enabled=False, title=title, theme=ui.theme) as shared.gradio['interface']:
  File "C:\Users\QUACK\Downloads\roooooflllll\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "C:\Users\QUACK\Downloads\roooooflllll\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "C:\Users\QUACK\Downloads\roooooflllll\oobabooga_windows\installer_files\env\lib\site-packages\gradio_client\serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'

**Comment by TCNOco** [comment]
Seems to be an issue with Oobabooga itself, rather than my install scripts.
Searching for `serialized_input` on the Issues section of Ooba, I came across this: https://github.com/oobabooga/text-generation-webui/issues/1855

This should have been solved with an update, so run `update_windows.bat`.

Otherwise can be fixed with `pip install gradio_client==0.1.4`
