### ISSUE TITLE
No file server.py and issues with webui.py

### ISSUE THREAD

**Issue by DominikMendoza** [TCNOco/TcNo-TCHT#7]
```
PS D:\Vicuna> iex (irm vicuna.tc.ht)
.
.
.
What version do you want to install?
A) NVIDIA
B) AMD (Detected)
C) Apple M Series
D) CPU-Only mode
Answer (A/B/C/D): D

Done!


Do you want desktop shortcuts for Oobabooga? (y/n): y
Downloading Oobabooga icon...

Creating shortcuts on desktop...

Pick which models to download:
CPU: 1
GPU [Nvidia]: 2
CPU + GPU [Nvidia]: 3
Enter a number: 1


Pick a CPU model and enter a number below?
- 13B (~9.8GB+ RAM): 1
-  7B (~5.8GB+ RAM): 2
- Both: 3
Enter choice: 1
Downloading CPU model 13B
Downloading: eachadea/ggml-vicuna-13b-1.1 (CPU model)
[#9f53bd 0B/0B CN:1 DL:0B]Done

Done!



Create desktop shortcuts for 'Vicuna' and 'Vicuna (CPU)'


Do you want desktop shortcuts? (y/n): y
Downloading Vicuna icon...

Creating shortcuts on desktop...



All set up. Which model should I launch?
- CPU version: 1
- GPU version: 2
- Exit: 3
Enter a number: 1
```

After installation:
I get the following python error:
```
can't open file 'D:\\Vicuna\\oobabooga_windows\\text-generation-webui\\server.py': [Errno 2] No such file or directory
```
(of course the file is not there)

and the following when I try to open the webui.py:
```
PS D:\Vicuna\oobabooga_windows> python .\webui.py
Traceback (most recent call last):
  File "D:\Vicuna\oobabooga_windows\webui.py", line 169, in <module>
    check_env()
  File "D:\Vicuna\oobabooga_windows\webui.py", line 41, in check_env
    if os.environ["CONDA_DEFAULT_ENV"] == "base":
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'CONDA_DEFAULT_ENV'
```

**Comment by TCNOco** [comment]
This seems to be related to: https://github.com/oobabooga/text-generation-webui/issues/1989
An issue on the Oobabooga repo itself.

But looking further I do see you can set variables such as this (and many others: )
Maybe try modifying this to point to the correct path and run it? 
```bash
cd D:\Vicuna\oobabooga_windows\
set CONDA_DEFAULT_ENV=D:\Vicuna\oobabooga_windows\installer_files\env
start_vicuna-cpu-7B.bat
```
Also edit the last start.bat to open the correct Vicuna model you have installed.

I'll be closing this issue, but feel free to respond :)
